// SPDX-License-Identifier: MIT
//
// Clause 22 MDIO PHY model.
//
// MDC is generated by the station, not by the testbench, so this model has no
// clock of its own: it watches for MDC edges from a system clock callback and
// works from those.  It holds a register file per PHY address, answers reads,
// and logs every write in order so a test can check not just what was written
// but when.
//
// Both sides change MDIO on the falling edge of MDC and sample on the rising
// edge, which is what wb_mdio does and what makes the bus readable in a
// waveform.  A real PHY has a wider window than that; nothing here depends on
// the difference.

#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "sim.h"

namespace wtb {

struct MdioPorts {
  uint8_t* mdc = nullptr;      // driven by the station
  uint8_t* mdio_o = nullptr;   // station output
  uint8_t* mdio_oe = nullptr;  // station drives when set
  uint8_t* mdio_i = nullptr;   // driven by this model
};

class MdioPhy {
 public:
  struct Write {
    u64 time_ps;
    uint8_t phyad;
    uint8_t regad;
    uint16_t value;
  };

  // sample_clk is any clock fast enough to see both MDC edges; the system
  // clock always is, since MDC is derived from it.
  MdioPhy(Sim& sim, Sim::Clock* sample_clk, MdioPorts ports, uint8_t addr = 1);

  uint16_t reg(uint8_t regad) const { return regs_[regad & 0x1f]; }
  void set_reg(uint8_t regad, uint16_t v) { regs_[regad & 0x1f] = v; }

  const std::vector<Write>& writes() const { return writes_; }
  void clear_writes() { writes_.clear(); }
  size_t reads() const { return reads_; }

  // How many times BMCR may be read with the reset bit still set before the
  // model clears it.  0 means the reset finishes immediately.
  void set_reset_reads(int n) { reset_reads_ = n; }

  // Frames whose PHY address is not ours are ignored, as a real PHY does.
  uint8_t address() const { return addr_; }

  // Set when a frame was seen that did not start with at least 32 ones.
  bool short_preamble_seen() const { return short_preamble_; }

 private:
  void tick();
  void on_rising(bool bit);
  void on_falling();

  enum class St { Preamble, St1, Op, PhyAd, RegAd, Ta, Data };

  Sim& sim_;
  MdioPorts p_;
  uint8_t addr_;

  bool prev_mdc_ = false;
  St st_ = St::Preamble;
  int ones_ = 0;
  int count_ = 0;
  uint8_t op_ = 0;
  uint8_t phyad_ = 0;
  uint8_t regad_ = 0;
  uint16_t data_ = 0;
  uint32_t out_ = 0;       // the read reply: a zero then sixteen data bits
  int out_bit_ = 0;
  bool driving_ = false;
  bool for_us_ = false;
  bool short_preamble_ = false;

  uint16_t regs_[32] = {0};
  std::vector<Write> writes_;
  size_t reads_ = 0;
  int reset_reads_ = 1;
  int reset_seen_ = 0;
};

}  // namespace wtb
